name: publish_and_notify

on:
  push:
    branches: [ patst ]
jobs:
  test_itself:
    name: Test Action-FTP-Deploy-Then-Slack-Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0

    - name: Get git-ftp ready
      run: git ftp > /dev/null 2>&1 || apt-get install -y git-ftp

    - name: Own afdtsn action (test)
      uses: objectdotnet/action-ftp-deploy-then-slack-notification@patst
      with:
        repo-root: test_site
        ftp-host: ${{ secrets.ftp_deploy_host }}
        ftp-user: ${{ secrets.ftp_deploy_user }}
        ftp-pass: ${{ secrets.ftp_deploy_pass }}
        ftp-root: ${{ secrets.ftp_deploy_root }}
        slack-webhook:  ${{ secrets.slack_webhook }}
        slack-to: ${{ secrets.slack_recipient }}
        slack-nickn: "Deploy Service"
        slack-icon: ":construction_worker:"